version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "80:80"
        volumes:
            - .:/var/www
        environment:
            - DB_HOST=db # Nome do serviço 'db', que é o hostname do contêiner
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            - db # Garantir que o serviço db seja iniciado primeiro
    db:
        image: mysql:5.7
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
